# Generated by Django 5.0.1 on 2024-02-06 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_answer_date_answer_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dependency_condition',
            field=models.TextField(default=None, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='depends_on',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='main.answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_branching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='first_question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_survey', to='main.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.survey'),
        ),
    ]
