# Generated by Django 5.0.1 on 2024-02-06 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_dependency_condition_question_depends_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='first_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_survey', to='main.question'),
        ),
    ]
