# Generated by Django 5.0.1 on 2024-02-08 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_survey_first_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dependency_condition',
            field=models.TextField(blank=True, default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='depends_on',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='main.answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.question'),
        ),
    ]
