# Generated by Django 5.0.1 on 2024-02-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_question_choices_question_is_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='right_text',
            field=models.TextField(blank=True, default=None, max_length=2048, null=True),
        ),
    ]
