# Generated by Django 5.0.1 on 2024-02-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_question_right_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='dependency_condition',
            new_name='right_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='right_choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='right_text',
        ),
    ]
