# Generated by Django 5.0.1 on 2024-02-10 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_dependency_condition_question_right_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='default_branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrongly_answered_question', to='main.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_question', to='main.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, default=None, max_length=2048, null=True),
        ),
    ]
